source "https://rubygems.org"

gem 'sinatra'
gem 'sinatra-contrib'
gem 'uglifier'
gem 'activesupport'
#gem 'dotenv'
#gem 'erubis'
gem 'rake'
gem 'redis-rack'
gem 'rack-mount'
#gem 'nokogiri'
#gem 'tilt-jbuilder'
gem 'typhoeus'
gem 'addressable'
gem 'compass'
gem 'rqrcode_png'
gem 'unicorn'