Fengtai: 丰台
Yanqing: 延庆
Huairou: 怀柔
Miyun: 密云
Mentougou: 门头沟
Changping: 昌平
Shunyi: 顺义
Pinggu: 平谷
Haidian: 海淀
Shijingshan: 石景山
Chaoyang: 朝阳
Xicheng: 西城
Dongcheng: 东城
Tongzhou: 通州
Fangshan: 房山
Daxing: 大兴
Beijing: 北京
Shenzhen: 深圳
Shanghai: 上海
Xiamen: 厦门
Nanjing: 南京
unknown: 未知