development:
   server_url: http://a8a07864.ngrok.io
   client_url: http://localhost:3031
   cdn_url: <%= ENV['SERVER_URL'] || 'http://localhost:3031' %>

test:
  server_url: http://localhost:3032
  client_url: http://localhost:3031

staging:
  client_url: <%= ENV['CLIENT_URL'] || 'http://client.usreclub.com' %>
  server_url: <%= ENV['SERVER_URL'] || 'http://api.usreclub.com' %>
  cdn_url: <%= ENV['CDN_URL'] || 'http://image.meejia.com/' %>

production:
  client_url: <%= ENV['CLIENT_URL'] || 'http://client.meejia.com' %>
  server_url: <%= ENV['SERVER_URL'] || 'http://api.meejia.com' %>
  cdn_url: <%= ENV['CDN_URL'] || 'http://image.meejia.com/' %>
