development:
   server_url: localhost:3032
   client_url: localhost:3031
   cdn_url: <%= ENV['SERVER_URL'] || 'http://mirror-10018786.file.myqcloud.com/' %>

test:
  server_url: http://localhost:3032
  client_url: http://localhost:3031

staging:
  client_url: <%= ENV['CLIENT_URL'] || 'http://client.usreclub.com' %>
  server_url: <%= ENV['SERVER_URL'] || 'http://api.usreclub.com' %>
  cdn_url: <%= ENV['CDN_URL'] || 'http://cdn.usreclub.com/' %>

production:
  client_url: <%= ENV['CLIENT_URL'] || 'http://client.meejia.cn' %>
  server_url: <%= ENV['SERVER_URL'] || 'http://api.meejia.cn' %>
  cdn_url: <%= ENV['CDN_URL'] || 'http://mirror-10018786.file.myqcloud.com/' %>
