development:
  server_url: http://81703363.ngrok.io

test:
  server_url: http://localhost:3032

staging:
  server_url: http://www.usreclub.com:3000

production:
  server_url: http://www.meejia.com:3000
